OSMT-300: Show categories with totals on collection detail pages.
wgu-opensource/osmt pull request #363
Opened 2023-04-17 02:45 UTC by trs-aaron

resolves https://github.com/wgu-opensource/osmt/issues/300

- Added KeywordCount to store a Keyword and total count.
- Added Map of all KeywordTypes to KeywordCounts that include all keywords and number of Skills with Keyword to Collection.
- Added Pill & PillGroup components to display Categories on Collection pages.
- Added Categories with counts to Collection public & manage pages.
- On Collection manage pages clicking on Category pill filters skills based on Category.

2023-04-17 19:31 UTC, ottonomy commented
@JohnKallies I'm seeing lots of ❌ across builds today https://github.com/wgu-opensource/osmt/pull/363 with the same error as the build from this PR. @trs-aaron indicates that the tests ran successfully on local, and given that this same error is occurring across other branches, it looks like it is not related to the commits in this PR.

2023-04-17 19:50 UTC, JohnKallies commented
@ottonomy @trs-aaron yes, we are having issues with our CI build in GitHub runners. We have been looking at this for several days now, and aren't getting very far (if you have any ideas, we'd love to hear them).

We acknowledge that the failure is not related to @trs-aaron's changes.

2023-04-18 16:40 UTC, trs-aaron commented
![collection-categories_manage_light](https://user-images.githubusercontent.com/122352357/232845844-4ec02cee-923d-43ef-9bce-f5697e6f6658.png)
![collection-categories_public_dark](https://user-images.githubusercontent.com/122352357/232845855-2e4f6716-3255-4aad-a205-4544101a6946.png)
![collection-categories_public_light](https://user-images.githubusercontent.com/122352357/232845872-9e879211-b340-48a8-8f66-76c44f54a796.png)
![collection-categories_manage_dark](https://user-images.githubusercontent.com/122352357/232845883-734b342e-c748-428d-9751-838d6ab3afd3.png)

2023-04-20 18:31 UTC, ottonomy commented
@JohnKallies The recent pr #262 caused some drift and at least a minor conflict based on the order that these PRs were reviewed and merged. Can your team cover merging your changes into this branch and resolving conflicts as part of your review?

2023-04-21 17:34 UTC, manuel-delvillar requested changes
We can have a collection where all RSDs are without categories, so in this case we can hide "categories"

<img width="1434" alt="Screenshot 2023-04-21 at 11 06 52" src="https://user-images.githubusercontent.com/68391066/233695035-30aab873-aa7a-42a2-a784-ad12109395f5.png">

<br>
If we have a collection with a lot of categories, I think we can have an expansion panel (collapse) or a "Show all / Show more" if you really want to see all pills.

![chrome-capture-2023-3-21 (1)](https://user-images.githubusercontent.com/68391066/233697368-d39ed862-69c2-416b-b7d3-6c0dec227dac.gif)

2023-04-24 16:35 UTC, manuel-delvillar commented on ui/src/app/core/pill/pill.component.ts
> +  onClick() {
Probably can be `onClick(): void` to have a type def on all methods.

2023-04-24 16:36 UTC, manuel-delvillar commented on ui/src/app/core/pill/group/pill-group.component.ts
> +  onPillClicked(pill: TValue) {
Probably can be `onPillClicked(): void` to have a type def on all methods.

2023-04-24 16:37 UTC, manuel-delvillar approved these changes
It's working, only there are comments (without required changes)

2023-04-25 19:29 UTC, merged