OSMT 3.0 Changelog
wgu-opensource/osmt pull request #423
Opened 2023-06-20 19:19 UTC by Corpratespaz

2023-06-20 19:37 UTC, JohnKallies commented on CHANGELOG.md
> +- Removed leading `'-'` character from URLs in export files
This was only in the "dev" Spring profile, FWIW...

2023-06-20 21:55 UTC, manuel-delvillar commented on CHANGELOG.md
> +- Protractor e2e (end-to-end) testing framework (deprecated & unused by OSMT)
TSLint & codelyzer were also removed, we can add that only if we want to be more detailed.

2023-06-20 21:56 UTC, manuel-delvillar commented on CHANGELOG.md
> +
New dependencies added related to `ESLint`

2023-06-21 17:11 UTC, JohnKallies commented
@Corpratespaz got us started with a great 1st draft here. I added some additional details from @psanchez-wgu. Still looking for an approval from the OSE team.

2023-06-21 17:23 UTC, wgu-edwin requested changes

2023-06-21 17:23 UTC, wgu-edwin commented on CHANGELOG.md
> +## Model Changes:
This header has a colon while the others do not. Could be a typo?

2023-06-21 17:32 UTC, wgu-edwin approved these changes
Looks good to me

2023-06-21 17:40 UTC, psanchez-wgu approved these changes

2023-06-21 17:41 UTC, merged